"""LLM fallback classifier — Phase 3.

Third (and final) classification layer. Called only on rows the rules layer
left as `unknown` AND where the local sklearn model is uncertain — i.e. its
P(AI) sits inside `[llm_fallback_local_uncertainty_low, local_model_ai_threshold)`.

Routes every call through the local LLM hub at `http://127.0.0.1:8000` using
the Anthropic SDK with the version-free model alias `claude_haiku`. No direct
vendor calls and no inline `claude -p` wrapper — the hub already does
subprocess management and host-routing.

Verdicts and replies are persisted to Supabase via the existing
`comments.verdict_source = 'llm'` column. The on-disk JSON cache here is a
per-machine performance optimisation only; the database is the truth-of-record.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import tempfile
from functools import lru_cache
from pathlib import Path
from typing import Optional

logger = logging.getLogger("engagement.classify.llm_fallback")

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


# ---------- Config ----------

def is_enabled(cfg: Optional[dict] = None) -> bool:
    """True if engagement.llm_fallback.enabled is set in config."""
    if cfg is None:
        from engagement.db.client import load_engagement_config
        cfg = load_engagement_config()
    return bool((cfg.get("llm_fallback") or {}).get("enabled"))


def _fallback_cfg() -> dict:
    from engagement.db.client import load_engagement_config
    block = (load_engagement_config().get("llm_fallback") or {})
    return {
        "enabled": bool(block.get("enabled", False)),
        "base_url": block.get("base_url", "http://127.0.0.1:8000"),
        "model": block.get("model", "claude_haiku"),
        "cache_path": block.get("cache_path", "engagement/classify/.llm_cache.json"),
        "timeout_seconds": int(block.get("timeout_seconds", 20)),
    }


# ---------- Client ----------

@lru_cache(maxsize=1)
def _client():
    from anthropic import Anthropic  # local import — optional dep at runtime
    cfg = _fallback_cfg()
    return Anthropic(
        api_key="local-dummy",
        base_url=cfg["base_url"],
        timeout=float(cfg["timeout_seconds"]),
    )


# ---------- Cache ----------

def _cache_path() -> Path:
    p = Path(_fallback_cfg()["cache_path"])
    if not p.is_absolute():
        p = REPO_ROOT / p
    return p


@lru_cache(maxsize=1)
def _load_cache() -> dict:
    p = _cache_path()
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as err:
        logger.warning("⚠️ llm cache load failed (%s) — starting fresh", err)
        return {}


def _save_cache(cache: dict) -> None:
    p = _cache_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".llm_cache.", suffix=".tmp", dir=str(p.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fp:
            json.dump(cache, fp, ensure_ascii=False, indent=2)
        os.replace(tmp, p)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _cache_key(comment: dict) -> str:
    text_norm = (comment.get("text") or "").strip().lower()
    commenter_url = comment.get("commenter_url") or ""
    h = hashlib.sha256(f"{commenter_url}|{text_norm}".encode("utf-8")).hexdigest()
    return h


# ---------- Prompt + parse ----------

_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)


_SYSTEM_PROMPT = (
    "You are a binary classifier deciding whether a single comment on a social "
    "media post was written by a human or generated by an AI/LLM/assistant. "
    "You return JSON ONLY — no prose, no code fences, no commentary. "
    "When you say a comment is AI, also draft a short, warm, sincere "
    "acknowledgement reply (one line, ≤120 chars) so the post author can "
    "copy-paste-send it in a single click."
)


def _user_prompt(comment: dict, rules_reasons: Optional[list[dict]]) -> str:
    text = (comment.get("text") or "").strip()
    commenter_url = comment.get("commenter_url") or ""
    display_name = comment.get("display_name") or ""
    first = display_name.split()[0] if display_name else "there"
    reasons_blob = json.dumps(rules_reasons or [], ensure_ascii=False)
    return (
        "Comment to classify:\n"
        f"<text>{text}</text>\n"
        f"<commenter_url>{commenter_url}</commenter_url>\n"
        f"<commenter_first_name>{first}</commenter_first_name>\n"
        "Rules-layer signals that already fired on this comment "
        "(may be empty — context only, not a verdict):\n"
        f"<rules_reasons>{reasons_blob}</rules_reasons>\n\n"
        "Return ONLY a JSON object on a single line with this exact shape:\n"
        '{"verdict":"ai"|"human","confidence":<0..1 float>,'
        '"suggested_reply":<string|null>,"reasoning":<string ≤140 chars>}\n'
        "Rules:\n"
        '- "verdict" must be exactly "ai" or "human".\n'
        '- "suggested_reply" MUST be a short warm acknowledgement when verdict=="ai" '
        "(e.g. \"Thanks " + first + "! 🙏\") and null when verdict==\"human\".\n"
        '- "reasoning" explains the call in ≤140 chars.\n'
    )


_REQUIRED_KEYS = {"verdict", "confidence", "suggested_reply", "reasoning"}


def _extract_json(text: str) -> Optional[dict]:
    if not text:
        return None
    cleaned = _FENCE_RE.sub("", text).strip()
    # The model sometimes wraps with extra prose; grab the first {...} block.
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start < 0 or end <= start:
        return None
    try:
        obj = json.loads(cleaned[start : end + 1])
    except Exception:
        return None
    if not isinstance(obj, dict) or not _REQUIRED_KEYS.issubset(obj.keys()):
        return None
    verdict = obj.get("verdict")
    if verdict not in ("ai", "human"):
        return None
    try:
        obj["confidence"] = float(obj["confidence"])
    except Exception:
        return None
    if not 0.0 <= obj["confidence"] <= 1.0:
        obj["confidence"] = max(0.0, min(1.0, obj["confidence"]))
    reply = obj.get("suggested_reply")
    if reply is not None and not isinstance(reply, str):
        obj["suggested_reply"] = str(reply)
    reasoning = obj.get("reasoning") or ""
    obj["reasoning"] = str(reasoning)[:200]
    return obj


# ---------- Public ----------

def classify_one(comment: dict, rules_reasons: Optional[list[dict]] = None) -> Optional[dict]:
    """Return `{verdict, confidence, suggested_reply, reasoning}` or None on failure.

    The cache + Anthropic client are constructed lazily so importing this module
    has zero side effects.
    """
    cfg = _fallback_cfg()
    if not cfg["enabled"]:
        return None

    key = _cache_key(comment)
    cache = _load_cache()
    hit = cache.get(key)
    if hit:
        logger.debug("💾 llm cache hit %s", key[:8])
        return hit

    try:
        msg = _client().messages.create(
            model=cfg["model"],
            max_tokens=200,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _user_prompt(comment, rules_reasons)}],
        )
    except Exception as err:
        logger.warning("⚠️ llm call failed (%s) — leaving row unknown", err)
        return None

    try:
        parts = msg.content or []
        text = "".join(getattr(p, "text", "") for p in parts).strip()
    except Exception as err:
        logger.warning("⚠️ llm response shape unexpected (%s)", err)
        return None

    parsed = _extract_json(text)
    if parsed is None:
        logger.warning("⚠️ llm response parse failed: %r", text[:200])
        return None

    cache[key] = parsed
    try:
        _save_cache(cache)
    except Exception as err:
        logger.warning("⚠️ llm cache save failed (%s) — verdict still returned", err)

    logger.info(
        "🤖 llm verdict %s conf=%.2f for %s",
        parsed["verdict"], parsed["confidence"], (comment.get("commenter_url") or "")[:60],
    )
    return parsed
